config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :reservations
  resources :products
  resources :articles
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/achievements', to: 'static_pages#achievements'
  get  '/contact', to: 'static_pages#contact'
  get  '/discussions', to: 'static_pages#discussions'
  get  '/faq', to: 'static_pages#faq'
  get  '/archive', to: 'static_pages#archive'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def achievements
  end

  def contact
  end

  def discussions
  end

  def archive
  end

  def faq
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/achievements.html.erb
<h1>StaticPages#achievements</h1>
<p>Find me in app/views/static_pages/achievements.html.erb</p>

app/views/static_pages/archive.html.erb
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h1 class="">Najpopulárnejšie témy</h1>
          <ul class="">
            <li>
              <a href="#">Proteín</a>
            </li>
            <li>
              <a href="#">Bicepsy</a>
            </li>
            <li>
              <a href="#">Triceps</a>
            </li>
            <li>
              <a href="#">Pevné zadočky</a>
            </li>
            <li>
              <a href="#">RAW strava</a>
            </li>
            <li>
              <a href="#">Kardio</a>
            </li>
            <li>
              <a href="#">Benchpress</a>
            </li>
            <li>
              <a href="#">Squats</a>
            </li>
            <li>
              <a href="#">Bielkoviny</a>
            </li>
            <li>
              <a href="#">BMI</a>
            </li>
            <li>
              <a href="#">Zranenie</a>
            </li>
            <li>
              <a href="#">Aminokyseliny</a>
            </li>
            <li>
              <a href="#">Strava</a>
            </li>
            <li>
              <a href="#">Svalovka</a>
            </li>
            <li>
              <a href="#">Burnout</a>
            </li>
            <li>
              <a href="#">Tréning</a>
            </li>
          </ul>
        </div>
        <div class="col-md-8">
          <p class="lead"><b>Je lezenie dobrý šport na rýchle chudnutie?</b></p>
          <ul class="">
            <li><b>Tréner:</b> Lezenie je zaujímavý outdoorový šport, nno nie je ideálny na chudnutie. Skôr by som odporúčal beh, prípadne nejaké kardio cviky v posilovni. Ak máte záujem, môžem Vám zostaviť osobný cvičebný plán.</li>
            <li><b>Robokop:</b> Ja som začal liesť nedávno a pribral som 5 kíl.</li>
      <a href="#">Čítaj viac</a>
          </ul>
      <br>
    <p class="lead"><b>Ideálny jedálniček na celý týždeň</b></p>
          <ul class="">
            <li><b>Rendy:</b> Ja uprednostňujem prestrú stravu než nejaký presne naplánovaný jedálniček. </li>
            <li><b>Tréner:</b> Pestrá strava je fajn ale pri cvičení je dobre prispôsobiť príjem niektorý zložiek tréningu. Napríklad ak podstupujete silový tréning je dobré obohatiť stravu o príjem bielkovin napr. si dať aspoň 3 krát do týždňa na večeru tvaroh.</li>
      <a href="#">Čítaj viac</a>
          </ul>     
      <br>
    <p class="lead"><b>Nezabúdajte cvičiť nohy</b></p>
          <ul class="">
            <li><b>Mihaljnica:</b> Presne!!! :D nieje nič horšie ako vidieť poriadne vymakaného človeka na dvoj tenkých paličkách :D :D </li>
            <li><b>Zaris:</b> Ono to nieje žeby som zabudol. Mne sa len proste neche :D Radšej si dám biceps.</li>
      <a href="#">Čítaj viac</a>
          </ul>
            <br>
    <p class="lead"><b>Najhoršie zážitky z posilky</b></p>
          <ul class="">
            <li><b>Ilirion:</b> Úplne najhoršie bolo keď som cvičil s trénerom, dával som si benchpress moju maximálku (vtedy 50KG) a on miesto toho aby ma istil sa obzeral po nejakých babách...som myslel že si tam zlomím krk.</li>
            <li><b>Tréner:</b> Fu to ma mrzí. Niečo také by sa naozaj stávať nemalo a môžem vám zaručiť že u mňa sa ani nestane. Svojou prácu beriem zodpovedne.</li>
      <a href="#">Čítaj viac</a>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/discussions.html.erb
<div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-1">Poradňa</h1>
          <br> </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <h1 class="">Najpopulárnejšie témy</h1>
          <ul class="">
            <li>
              <a href="#">Proteín</a>
            </li>
            <li>
              <a href="#">Bicepsy</a>
            </li>
            <li>
              <a href="#">Triceps</a>
            </li>
            <li>
              <a href="#">Pevné zadočky</a>
            </li>
            <li>
              <a href="#">RAW strava</a>
            </li>
            <li>
              <a href="#">Kardio</a>
            </li>
            <li>
              <a href="#">Benchpress</a>
            </li>
            <li>
              <a href="#">Squats</a>
            </li>
            <li>
              <a href="#">Bielkoviny</a>
            </li>
            <li>
              <a href="#">BMI</a>
            </li>
            <li>
              <a href="#">Zranenie</a>
            </li>
            <li>
              <a href="#">Aminokyseliny</a>
            </li>
            <li>
              <a href="#">Strava</a>
            </li>
            <li>
              <a href="#">Svalovka</a>
            </li>
            <li>
              <a href="#">Burnout</a>
            </li>
            <li>
              <a href="#">Tréning</a>
            </li>
          </ul>
        </div>
        <div class="col-md-8">
          <h1 class="">Aktívna diskusia</h1>
          <p class="lead"><b>Je lezenie dobrý šport na rýchle chudnutie?</b></p>
          <ul class="">
            <li><b>Tréner:</b> Lezenie je zaujímavý outdoorový šport, nno nie je ideálny na chudnutie. Skôr by som odporúčal beh, prípadne nejaké kardio cviky v posilovni. Ak máte záujem, môžem Vám zostaviť osobný cvičebný plán.</li>
            <li><b>Robokop:</b> Ja som začal liesť nedávno a pribral som 5 kíl.</li>
            <ul class="">
              <li><b>Mihaljnica:</b> Je to dosť aj o strave.</li>
              <li><b>Mates-san:</b> Hej, je to dobré na nabratie svalov v horných partiách.</li>
            </ul>
            <li><b>Zaris:</b> Ja lozím celý život a je to super na udržiavanie kondície</li>
            <ul class="">
              <li><b>Ilirion:</b> ľudom na nervy</li>
              <ul class="">
                <li><b>Rendy:</b> #rekt</li>
                <li><b>Zaris:</b> :D :D</li>
              </ul>
            </ul>
            <ul class="">
              <li><b>Topa:</b> Ja som si rozbil hlavu pri lezení</li>
            </ul>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <%= link_to "<i class='fa fa-fw fa-question-circle-o'></i>".html_safe + 'Často kladené otázky', faq_url, class: "btn btn-primary btn-lg btn-block" %>
          <br>
          <br>
          <%= link_to "<i class='fa fa-fw fa-archive'></i>".html_safe + 'Archív diskusií', archive_url, class: "btn btn-primary btn-lg btn-block" %>
        </div>
           <div class="col-md-9">
            <div class="panel panel-primary">
              <div class="panel-heading"><h2>Live Chat</h2></div>
              <div class="panel-body">
                    <div class="chat-body clearfix">
                      <div class="header"> <strong class="primary-font">Peter Silný</strong> <small class=" text-muted">
                                        <span class="glyphicon glyphicon-time"></span>12 mins ago</small> </div>
                      <p> Okej, ďakujem. V tomto prípade by som teda odporúčal&nbsp;CASEIN ZERO.&nbsp;Pomaly sa vstrebávajúci kazeínový proteínový prášok bez laktózy, gluténu a cukru vhodný pre ľudí, ktorí často cvičia.</p>
                    </div>
                    <div class="chat-body clearfix">
                      <div class="header"> <strong class=" primary-font">Dávid Kažimír</strong>  <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>13 mins ago</small> </div>
                      <p> Moja hmotnosť je 75 kg a cvičím 4x do týždňa</p>
                    </div>
                    <div class="chat-body clearfix">
                      <div class="header"> <strong class="primary-font">Peter Silný</strong> <small class=" text-muted">
                                        <span class="glyphicon glyphicon-time"></span>14 mins ago</small> </div>
                      <p> Zdravím, potrebujem vedieť o Vás akú máte hmotnosť a koľkokrát do týždňa cvičíte.</p>
                    </div>
                    <div class="chat-body clearfix">
                      <div class="header"> <strong class=" primary-font">Dávid Kažimír</strong> <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>15 mins ago</small> </div>
                      <p> Dobrý deň, chcel by som sa opýtať aké výživové doplnky odporúčate pre 18 ročného študenta.
                        <br> </p>
                    </div>
              </div>
              <div class="panel-footer">
                <div class="input-group mx-1">
                  <input id="btn-input" type="text" class="form-control input-sm" placeholder="Správa"> <span class="input-group-btn">
                            <button class="btn btn-sm btn-secondary" id="btn-chat">Poslať</button>
                        </span> </div>
              </div>
            </div>
          </div>  
      </div>
    </div>
  </div>

app/views/static_pages/faq.html.erb
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-1">Často kladené otázky</h1>
          <br> </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <h1 class="">Najpopulárnejšie témy</h1>
          <ul class="">
            <li>
              <a href="#">Proteín</a>
            </li>
            <li>
              <a href="#">Bicepsy</a>
            </li>
            <li>
              <a href="#">Triceps</a>
            </li>
            <li>
              <a href="#">Pevné zadočky</a>
            </li>
            <li>
              <a href="#">RAW strava</a>
            </li>
            <li>
              <a href="#">Kardio</a>
            </li>
            <li>
              <a href="#">Benchpress</a>
            </li>
            <li>
              <a href="#">Squats</a>
            </li>
            <li>
              <a href="#">Bielkoviny</a>
            </li>
            <li>
              <a href="#">BMI</a>
            </li>
            <li>
              <a href="#">Zranenie</a>
            </li>
            <li>
              <a href="#">Aminokyseliny</a>
            </li>
            <li>
              <a href="#">Strava</a>
            </li>
            <li>
              <a href="#">Svalovka</a>
            </li>
            <li>
              <a href="#">Burnout</a>
            </li>
            <li>
              <a href="#">Tréning</a>
            </li>
          </ul>
        </div>
        <div class="col-md-8">
          <h3 class="">Ako a kde začať?</h1>
          <ul class="">
            <li>Ja odporúčam tieto tri základné veci: dieta má 80-90% podiel na premene vášho tela, nepodceňujte ju a dietou rozhodne nemyslím hladovku ale stravu primeranú vašej fyzickej činnosti. Druhým kľúčom je nájsť si aktivitu, ktorá vás baví. Nemá zmysel sa potiť v posilke ak vás to nebaví. Zato ak máte radi plávanie tak smelo do toho. A tretia vec, ktorú je dobre si uvedomiť je, že vďaka silovému tréningu bude všetko vo vašom živote ĽAHŠIE!</li>
          </ul>
      <br>
          <h3 class="">Je dobré robiť kardio a silový tréning naraz ? </h1>
          <ul class="">
            <li>Jasné! Smelo do toho. Kľudne si dajte silový tréning a za tým trochu kardia. Alebo pondelok, streda, piatok silový tréning a utorok štvrtok nejaká zábavná aktivita, ktorá vám rozpumpuje srdce.</li>
          </ul>
      <br>
    <h3 class="">Počul som žeby som mal jesť viacero jedál denne. Čo je na tom pravdy?</h1>
          <ul class="">
            <li>Raňajky vždy! Je dobré jesť aspoň každé tri hodiny a tak aby sa strava skladala z 30-40% proteíny, 30-40% karbohydráty a 10-20% tuky. Jedzte 30-60 minút pred cvičením a znova 30-60 minút po cvičení.</li>
          </ul>
      <br>
    <h3 class="">Koľko vody by som mala vypiť denne ? </h1>
          <ul class="">
            <li>Doktory odporúčajú aspoň 2 litre denne. Čím je však človek väčší tým viac vody by mal vypiť a počas horúcich dni ešte viac. Ak máte daný deň tréning tak tiež odporúčam piť viac.</li>
          </ul>
      <br>
    <h3 class="">Potrebujem pás na vzpieranie ?</h1>
          <ul class="">
            <li>Je vysoko odporúčané používať kvalitný, kožený pás, ktorý vám spevní spodnú časť chrbtice a tým predchádza zraneniu. Ja osobne ho používam vždy a nemám žiadne prolémy s chrbticou.</li>
          </ul>
      <br>
        </div>
      </div>
    </div>
  </div>

app/views/static_pages/home.html.erb
<div class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-3 my-4">Novinky</h1>
          <div class="row">
            <div class="col-md-1"><i class="d-block  fa fa-5x fa-info text-center bg-warning my-2"></i></div>
            <div class="col-md-11">
              <h2>Dostupnosť počas Vianočných sviatkov</h2>
              <p class="">Dovoľujem si Vás informovať o dostupnosti služieb počas Vianoc a Nového roku 2017. Dňa 25. Decembra je sviatok a nebude možné využívať moje služby. Dostupnosť v štandardnom režime bude od 25.12.2017 do 30.12.2017. Dňa 31.12.2017 až 2.1.2018 služby neposkytujem a štandardný režim nastupuje opäť od 3.1.2017. Teším sa na Vás a prajem Vám príjemné prežitie vianočných sviatkov.</p>
            </div>
          </div>
        </div>
      </div>
      <br>
      <br>
    </div>
      <div class="row">
        <div class="col-md-4">
          <img class="img-fluid d-block" src="https://fitnesstrainer.imgix.net/uploads/instructor/picture/11191/2ad77e38479accabe7a74302920a5395-profile-small.png?auto=format%2Cenhance%2Credeye&amp;s=e1e46935f9e9f75fbe696e5a2d2049d4" alt="Fotka trénera"> </div>
        <div class="col-md-8">
          <h2 class="">O mne</h2>
          <p class="">Od štyroch rokov sa venujem športu. Pätnásť rokov som aktívne hrával ľadový hokej za Slovan Bratislava. Popri hokeji som vyskúšal doplnkové športy: gymnastiku, tenis, futbal a box. Na konci mojej hokejovej kariéry som si uvedomil, že tento rýchlostno
            - silový šport si vyžaduje mimoriadnu pozornosť, ktorá by mala byť zameraná predovšetkým na kompenzáciu jednostranného zaťaženia a odstránenie svalových dysbalancií.&nbsp;
            <br>Spojil som sa s fyzioterapeutom a začal som vykonávať doplnkové športy, aby som nadobudol komplexnosť pohybových schopností. Naša spolupráca trvá dodnes a táto problematika sa zároveň stala mojím koníčkom.
            <br>Pri štúdiu na Univerzite Komenského - Fakulte telesnej výchovy a športu v Bratislave som si vybral špecializáciu trénerstvo - kondičný tréner a nadobudnuté vzdelanie sa usilujem zlepšovať prostredníctvom rôznych školení a kurzov. Svojim klientom
            sa snažím poskytnúť maximálnu komplexnú starostlivosť. Prioritou je pre mňa Vaša spokojnosť a dosiahnutie spoločne vytýčeného cieľa.</p>
        </div>
      </div>
    <div class="py-5">
      <div class="container">
        <div class="row my-5">
          <div class="col-md-12">
            <div class="embed-responsive embed-responsive-16by9 w-75 mx-auto">
              <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/kUGxgmRcwX0" allowfullscreen=""> </iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>