config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :reservations
  resources :products
  resources :articles
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/achievements', to: 'static_pages#achievements'
  get  '/contact', to: 'static_pages#contact'
  get  '/discussions', to: 'static_pages#discussions'
  get  '/faq', to: 'static_pages#faq'
  get  '/archive', to: 'static_pages#archive'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	validates :quantity,  presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to User.find(@order.user_id), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { redirect_to Product.find(@order.product_id), notice: 'Order was not successfully created.' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :product_id, :quantity)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :product_id, :value => params[:product_id] %>

  <%= f.hidden_field :user_id, :value => params[:user_id] %>

  <div class="field">
    <b>Počet</b>
    <%= f.number_field :quantity %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit "Objednať", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user %></td>
        <td><%= order.product %></td>
        <td><%= order.quantity %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<% if logged_in? %>
	<h1>Objednanie</h1>
	<%= render 'form', order: @order %>
<% else %>
	<h1>Na objednanie tovaru sa prihláste.</h1>
<% end %>

app/views/orders/show.html.erb
<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.product_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>