config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :reservations
  resources :products
  resources :articles
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/achievements', to: 'static_pages#achievements'
  get  '/contact', to: 'static_pages#contact'
  get  '/discussions', to: 'static_pages#discussions'
  get  '/faq', to: 'static_pages#faq'
  get  '/archive', to: 'static_pages#archive'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	def start_time
        self.term
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservations = Reservation.all
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to User.find(@reservation.user_id) }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:course, :user_id, :term)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :course, :value => params[:course_id] %>

  <%= f.hidden_field :user_id, :value => params[:user_id] %>

  <%= week_calendar events: @reservations do |date, reservations| %>
    <% [ 8, 10, 14, 16, 18 ].each do |time| %>
      <% if !reservations.map(&:term).flatten.include?(DateTime.parse("#{date} #{time}:00:00.000000")) %>
        <br><%= f.radio_button :term, DateTime.parse("#{date} #{time}:00:00.000000") %>
        <%= "#{time}:00" %>
      <% else %>
        <br><%= f.radio_button :term, DateTime.parse("#{date} #{time}:00:00.000000"), :disabled => true %>
        <%= "obsadené" %>
      <% end %>
    <% end %>
  <% end %>

  <br>

  <div class="actions">
    <%= f.submit "Rezervovať", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<div class="py-4">
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="py-5 bg-dark">
        <h1 class="text-center"><%= link_to 'Kondičný tréning', new_reservation_path(:user_id => current_user, :course_id => 1), class: "text-white" %></h1>
      </div>
      <%= link_to image_tag("https://thumb.ibb.co/dAOO8G/fitness_tamara_ukradena.jpg", class: "img-fluid d-block", width: "690", height: "460", alt: "Ilustračný obrázok 1"), new_reservation_path(:user_id => current_user, :course_id => 1) %>
      <%= link_to 'Prihlásiť sa (19,99 €)', new_reservation_path(:user_id => current_user, :course_id => 1), class: 'btn btn-primary btn-lg btn-block' %>
    </div>
    <div class="col-md-4">
      <div class="py-5 bg-dark">
        <h1 class="text-center"><%= link_to 'Začiatočník', new_reservation_path(:user_id => current_user, :course_id => 2), class: "text-white" %></h1>
      </div>
      <%= link_to image_tag("https://thumb.ibb.co/inWkoG/barbell_back_squat_main_0.jpg", class: "img-fluid d-block", width: "690", height: "460", alt: "Ilustračný obrázok 2"), new_reservation_path(:user_id => current_user, :course_id => 2) %>
      <%= link_to 'Prihlásiť sa (29,99 €)', new_reservation_path(:user_id => current_user, :course_id => 2), class: 'btn btn-primary btn-lg btn-block' %>
    </div>
    <div class="col-md-4">
      <div class="py-5 bg-dark">
        <h1 class="text-center"><%= link_to 'Pokročilý', new_reservation_path(:user_id => current_user, :course_id => 3), class: "text-white" %></h1>
      </div>
      <%= link_to image_tag("https://thumb.ibb.co/m4hVNb/bodybuilder_bicep_flex_holiday_workout.jpg", class: "img-fluid d-block", width: "690", height: "460", alt: "Ilustračný obrázok 3"), new_reservation_path(:user_id => current_user, :course_id => 3) %>
      <%= link_to 'Prihlásiť sa (49,99 €)', new_reservation_path(:user_id => current_user, :course_id => 3), class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  </div>
</div>
<div class="py-5">
  <div class="container">
    <div class="row my-5">
      <div class="col-md-12">
        <h1 class="bg-dark text-white text-center">Cenník vstupov do fitness centra</h1>
        <img class="img-fluid d-block mx-auto" src="https://preview.ibb.co/cSmqNb/cennik.png" width="" height="" alt="Cenník vstupov"> </div>
    </div>
    <div class="row my-5">
      <div class="col-md-12">
        <h1 class="bg-dark text-white text-center">Cenník ďalších ponúkaných služieb</h1>
        <img class="img-fluid d-block mx-auto" src="https://preview.ibb.co/e0Dn2b/cennik2.png" alt="Cenník ďalších služieb"> </div>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<% if logged_in? %>
	<h1>Rezervácia</h1>
	<%= render 'form', reservation: @reservation %>
<% else %>
	<h1>Pre zapísanie na kurz sa prihláste.</h1>
<% end %>

app/views/reservations/show.html.erb
<p>
  <strong>Course:</strong>
  <%= @reservation.course %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<p>
  <strong>Term:</strong>
  <%= @reservation.term %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>