config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :reservations
  resources :products
  resources :articles
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/achievements', to: 'static_pages#achievements'
  get  '/contact', to: 'static_pages#contact'
  get  '/discussions', to: 'static_pages#discussions'
  get  '/faq', to: 'static_pages#faq'
  get  '/archive', to: 'static_pages#archive'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="sk">
  <head>
    <title>OsobnyTrener</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <nav class="navbar navbar-expand-md bg-primary navbar-dark">
	    <div class="container">
	      <%=link_to "Osobný Tréner Peter Silný", root_url, class: "navbar-brand", id: "logo" %>
	      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span> </button>
	      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
	      	<a class="btn navbar-btn btn-primary ml-2 text-white"><i class="fa d-inline fa-lg fa-user-circle-o"></i>
		      <% if logged_in? %>
              <%=link_to current_user.name, current_user, class: "btn btn-lg btn-primary" %> / <%=link_to "Odhlásenie", logout_path, method: :delete, class: "btn btn-lg btn-primary" %>
       		<% else %>
	        &nbsp;<%=link_to "Prihlásenie", login_path, class: "btn btn-lg btn-primary" %> / <%=link_to "Registrácia", signup_path, class: "btn btn-lg btn-primary" %>
	        <% end %>
	        <br>
	    	</a>
	      </div>
	    </div>
	  </nav>
	  <div class="opaque-overlay" style="background-image: url(&quot;http://o.aolcdn.com/images/dims?thumbnail=1200%2C630&image_uri=http%3A%2F%2Fi.huffpost.com%2Fgen%2F2829756%2Fimages%2Fo-CHEETAH-facebook.jpg&client=cbc79c14efcebee57402&signature=970a0c7913674efbb0eb5760fdb8c2cd5369b7ff&quot;)">
	    <div class="text-left">
	      <div class="container">
	        <div class="row">
	          <div class="col-md-12 text-right">
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	            <br>
	          </div>
	        </div>
	      </div>
	    </div>
	  </div>
	  <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
	    <div class="container">
	      <%= link_to '<i class="fa fa-fw fa-home"></i>'.html_safe + "Domov", root_url, class: "navbar-brand" %>
	      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span> </button>
	      <div class="collapse navbar-collapse" id="navbarSupportedContent">
	        <ul class="navbar-nav mr-auto">
	          <li class="nav-item">
	          	<%= link_to '<i class="fa fa-fw fa-calendar"></i>'.html_safe + "Kurzy", reservations_url, class: "nav-link text-white" %>
	          </li>
	          <li class="nav-item">
	          	<%= link_to '<i class="fa fa-fw fa-shopping-cart"></i>'.html_safe + "E-Shop", products_url, class: "nav-link text-white" %>
	          </li>
	          <li class="nav-item">
	          	<%= link_to '<i class="fa fa-fw fa-book"></i>'.html_safe + "Články", articles_url, class: "nav-link text-white" %>
	          </li>
	          <li class="nav-item">
	          	<%= link_to '<i class="fa fa-fw fa-users"></i>'.html_safe + "Diskusné fórum", discussions_url, class: "nav-link text-white" %>
	          </li>
	          <li class="nav-item">
	            <%= link_to '<i class="fa fa-fw fa-user"></i>'.html_safe + "Moje úspechy", achievements_url, class: "nav-link text-white" %>
	          </li>
	          <li class="nav-item">
	          	<%= link_to '<i class="fa fa-fw fa-address-book"></i>'.html_safe + "Kontakt", contact_url, class: "nav-link text-white" %>
	          </li>
	        </ul>
	        <a href="https://www.facebook.com" target="_blank" aria-label="Odkaz na Facebook účet"><i class="fa fa-3x fa-facebook"></i>  </a>
            <a href="https://twitter.com" target="_blank" aria-label="Odkaz na Twitter účet"><i class="fa fa-3x fa-twitter"></i>  </a>
            <a href="https://www.instagram.com" target="_blank" aria-label="Odkaz na Instagram účet"><i class="fa fa-3x fa-instagram"> </i></a>
            <a href="https://www.youtube.com" target="_blank" aria-label="Odkaz na Youtube účet"><i class="fa fa-3x fa-youtube-play"></i></a>
	      </div>
	    </div>
	  </nav>
	<div class="py-5">
    	<div class="container">
  			<%= yield %>
  		</div>
  	</div>
  	<div class="py-5 bg-dark text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-6 text-center align-self-center">
          <p class="mb-5"> <strong>Sypač Inc.</strong>
            <br>Košická 17180/49,&nbsp;
            <br>Bratislava 1
            <br>
            <u>0908 148 818</u>
          </p>
          <div class="my-3 row">
            <div class="col-4 col-md-3">
              <a href="https://www.facebook.com" target="_blank" aria-label="Odkaz na Facebook účet"><i class="fa fa-3x fa-facebook"></i></a>
            </div>
            <div class="col-4 col-md-3">
              <a href="https://twitter.com" target="_blank" aria-label="Odkaz na Twitter účet"><i class="fa fa-3x fa-twitter"></i></a>
            </div>
            <div class="col-4 col-md-3">
              <a href="https://www.instagram.com" target="_blank" aria-label="Odkaz na Instagram účet"><i class="fa fa-3x fa-instagram"></i></a>
            </div>
            <div class="col-4 col-md-3">
              <a href="https://www.youtube.com" target="_blank" aria-label="Odkaz na Youtube účet"><i class="fa fa-3x fa-youtube-play"></i></a>
            </div>
          </div>
        </div>
        <div class="col-md-6 p-0">
          <img class="img-fluid" src="https://maps.googleapis.com/maps/api/staticmap?key=AIzaSyDW8nO9JhT_pEjebobq9pgUF2cEp0EUb1I&amp;markers=Ko%C5%A1ick%C3%A1+17180%2F49%2C+821+08+Bratislava&amp;center=Ko%C5%A1ick%C3%A1+17180%2F%0A49%2C+821+08+Bratislava&amp;zoom=16&amp;size=640x300&amp;sensor=false&amp;scale=2" alt="Mapa s lokáciou fitness centra"></div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>